language: android
android:
  components:
  # The SDK version used to compile your project
  - android-28
  # The BuildTools version used by your project
  - build-tools-27.0.3

# Accept all sdk licenses
before_install:
  yes | sdkmanager --licenses

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease